### ISSUE TITLE
Display a list of 10 random Wikipedia pages through the MediaWiki API

### ISSUE THREAD

**Issue by yureative** [urelx/reactive-wikipedia-reader#4]
#1
## Tasks
- [x] Create a page to list
- [x] Display dummy titles on the page
- [x] Fetch 10 random pages through the MediaWiki API
- [x] Display fetched pages' title on the page
- [ ] ~~Write test cases~~
