### ISSUE TITLE
Each item in a list page should have a title and it should be clickable

### ISSUE THREAD

**Issue by yureative** [urelx/reactive-wikipedia-reader#6]
#1
## Tasks
- [x] Create a detail page
- [x] Add a link to back to the list page
- [x] Make items be linkable to its detail page
- [x] Display an item's title on its detail page
