### ISSUE TITLE
Display categories and images on click of an item

### ISSUE THREAD

**Issue by yureative** [urelx/reactive-wikipedia-reader#7]
#1
## Tasks
- [x] Fetch detail of an item from the MediaWiki API
- [x] Display categories on a detail page
- [x] Display images on a detail page
