### ISSUE TITLE
User should be able to bookmark a page(item) in the app

### ISSUE THREAD

**Issue by yureative** [urelx/reactive-wikipedia-reader#8]
#1
## Tasks
- [x] Create a bookmark page
- [x] Add a menu link to the bookmark page (list and detail page)
- [x] Add a link to back to the list page
- [x] Add a bookmark button on a detail page
- [x] Add an item to the bookmark list (in the local storage) when the button is clicked
- [x] Make bookmark links be link to its detail page
- [x] Display bookmarked items on the bookmark page
